### ISSUE TITLE
Algorithm reference

### ISSUE THREAD

**Issue by tysonwu** [FL33TW00D/rustDTW#10]
Great project!
I am personally implementing DTW for use in an audio-related project. I notice there are several variations of the DTW algorithm, so I would like to know if there are any references on the algorithm this project is based-on. Thank you beforehand!

**Comment by FL33TW00D** [comment]
@tysonwu I have no idea what the implementation was based off to be honest, but as far as I recall it's just bog standard DTW.

**Comment by tysonwu** [comment]
No worries!
